### ISSUE TITLE
Can't start or stop mongod

### ISSUE THREAD

**Issue by cdmiller** [ivanvc/mongodb-prefpane#5] opened 2012-12-14 19:56 UTC
Just trying this prefpane on an existing mongo installation, and it correctly detects that mongod is running when I start/stop mongod from the command line, but using the on/off button has no effect.

I'm using MacOS 10.8.2

Here's my mongo installation and usual startup routine:
# which mongod

/usr/local/bin/mongod
# mongod --version

db version v2.0.6, pdfile version 4.5
Fri Dec 14 14:49:50 git version: e1c0cbc25863f6356aa4e31375add7bb49fb05bc
# sudo mongod

Password:
mongod --help for help and startup options
Fri Dec 14 14:51:39 [initandlisten] MongoDB starting : pid=8170 port=27017 dbpath=/data/db/ 64-bit host=private1.local
Fri Dec 14 14:51:39 [initandlisten] db version v2.0.6, pdfile version 4.5
Fri Dec 14 14:51:39 [initandlisten] git version: e1c0cbc25863f6356aa4e31375add7bb49fb05bc
Fri Dec 14 14:51:39 [initandlisten] build info: Darwin erh2.10gen.cc 9.8.0 Darwin Kernel Version 9.8.0: Wed Jul 15 16:55:01 PDT 2009; root:xnu-1228.15.4~1/RELEASE_I386 i386 BOOST_LIB_VERSION=1_40
Fri Dec 14 14:51:39 [initandlisten] options: {}
Fri Dec 14 14:51:39 [initandlisten] journal dir=/data/db/journal
Fri Dec 14 14:51:39 [initandlisten] recover : no journal files present, no recovery needed
Fri Dec 14 14:51:39 [websvr] admin web console waiting for connections on port 28017
Fri Dec 14 14:51:39 [initandlisten] waiting for connections on port 27017

Is this a known issue?  I've also tried https://github.com/remysaissy/mongodb-macosx-prefspane with similar results (detects the running service but can't start or stop it).

**Comment by ivanvc** [comment] 2012-12-14 21:52
Ah, I think it's because you need to run mongod with super user permissions, and currently it doesn't support that. It's very probable that this is the problem, however, will try to reproduce it, and release a fix for this issue.

By the way, this is the first time that I hear about mongodb-macosx-prefspane :stuck_out_tongue_winking_eye:.

Thanks for your feedback!

**Comment by cdmiller** [comment] 2012-12-14 22:24
Thanks, I was beginning to suspect that the super user permissions were the problem, I'm glad for the confirmation that the pref pane can't handle that.  I'm using mongo on my personal (MacOS) development machine, so I'll try to change the mongo database setup to run as a a local (non-su) user only.  Our production web app server is Linux (naturally enough).

**Closed as not planned** 2023-12-13 07:20 UTC
